### ISSUE TITLE
Exe does not seem to work

### ISSUE THREAD

**Issue by TorchicTortilla** [byvar/gaxm#2]
I don't know jack about code so this is probably only an issue I'm experiencing, but whenever I try to run the exe or place a game over it, I don't get anything but a command prompt that quickly fades away, I'm not sure if there's something wrong with what I downloaded, if I'm missing something that I should've downloaded or my incompetence.

**Comment by RayCarrot** [comment]
It's a command-line app, so you need to run it from cmd with launch arguments. The easiest way to do so is to open the folder where you downloaded the exe and in the file explorer address bar type `cmd` and hit enter. This will open cmd in the current directory. Then you can type the name of the exe (`gaxm` by default) to run it. If you don't specify any launch arguments you'll see a list of what is available. For example if you want to run it on a GBA rom you can type `gaxm -i rom.gba` where `rom.gba` is the file name of the GBA rom.
